name: Alpha build

on:
  push:
    tags: [alpha-v*]

jobs:
  build-native-exe:
    name: Build native messaging
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python v3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Upgrade pip
      run: py -m pip install --upgrade pip
    - name: setup development
      run: py 1-setup-dev-conan.py
    - name: build the project
      run: py 2-build-conan.py
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Alpha(1) - v0.5.1
        body: |-
          Added extended error message as base64 after 'Bad Request: '
        draft: true
        prerelease: true
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: installation\ksmgmnt.msi
        asset_name: ksmgmnt.msi
        asset_content_type: application/zip
    - name: set upload_url
      id: set_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: set
        key: url
        value: ${{ steps.create_release.outputs.upload_url }}

  build-ff-ext:
    name: Build Firefox Extension
    needs: build-native-exe
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install web-ext Firefox
      run: sudo npm --global install web-ext
    - name: web-ext lint
      run: |
        cd extensions/firefox/extension
        web-ext lint -v -s . 
    - name: web-ext build
      run: |
        cd extensions/firefox/extension
        web-ext build -v -s . --overwrite-dest
    - name: get upload_url
      id: get_upload_url
      uses: noobly314/share-data@v1
      with:
        share-id: release_url
        mode: get
        key: url
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_upload_url.outputs.data }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: extensions/firefox/extension/web-ext-artifacts/windows_crypto_key_generation-0.5.1a1.zip
        asset_name: windows_crypto_key_generation-0.5.1a1.zip
        asset_content_type: application/zip


